site_name: MPEI
site_description: MPEI students open library
site_author: Aladdin
site_url: https://mpei.space/

repo_url: https://github.com/Alaladdin/MPEI/
edit_uri: edit/main/docs/
copyright: By <a href="https://github.com/Alaladdin/"  target="_blank" rel="nofollow noopener">Alaladdin</a>

theme:
  name: material
  custom_dir: overrides
  language: ru
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple

  features:
    - navigation.tabs
    - navigation.sections

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library
    repo: fontawesome/brands/github-alt

# google_analytics: [ 'G-71TRV5BECW', '' ]
tag_manager: 'GTM-KFJSDNH'

markdown_extensions:
  - admonition
  - abbr
  - toc:
      permalink: '#'

  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.details
  #  - pymdownx.tasklist
  #  - pymdownx.emoji

plugins:
  - search
  - awesome-pages
  - macros
  - git-revision-date-localized:
      type: timeago
      time_zone: Europe/Moscow
      locale: ru

  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

extra_css:
  - 'assets/css/main.css'